version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true
